---
- hosts: localhost
  tasks:
    - name: Add Provider
      manageiq_provider:
        name: 'VMWare-Provider'
        type: 'VMware'
        state: 'present'
        provider:
          hostname: 'vcenter-et.gsslab.pnq2.redhat.com'
          userid: 'administrator@vsphere.local'
          password: 'RedHat1!'
        manageiq_connection:
          url: 'https://10.74.253.115'
          username: 'admin'
          password: 'smartvm'
          verify_ssl: False
...
