---
- hosts: localhost
  tasks:
  - name: Add User in MIQ
    manageiq_user:
      userid: 'user'
      name: 'User One'
      password: 'user'
      group: 'EvmGroup-user'
      email: 'h@r.com'
      manageiq_connection:
        url: 'http://127.0.0.1'
        username: 'admin'
        password: 'smartvm'
        verify_ssl: False
